### ISSUE TITLE
subtasks (up to 2023.02)

### ISSUE THREAD

**Issue by hjun-park** [hansol-cop32/weekly-plan-backend#3]
#### 우선순위 순으로 subtask 작성

<br />

- [ ] AWS 계정 생성 -> RDS 생성
- [ ] JWT 토큰 관리 목적 Redis 생성  (docker swarm 이용)
    - [ ]  추후 redis 이중화 혹은 백업 고려
- [ ] position (직급) CRUD  개발
- [ ] 테스트 코드 작성

**Comment by hjun-park** [comment]
1. Docker Compose ( Redis, MariaDB, Boot ) 작성 완료, Node.js는 미완료
